<?php

use Illuminate\Database\Seeder;
use App\Course;

class CoursesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $courses = [
            ['code' => 'SSBT with BRM','description' => 'Ship Simulator and Bridge Teamwork with BRM','category' => 'Deck','duration' => '5','branch_id' => '2','created_by' => '1'],
            ['code' => 'STSM','description' => 'Ship Handling & Maneuvering in Critical Conditions (Advance SSBT)','category' => 'Deck','duration' => '5','branch_id' => '2','created_by' => '1'],
            ['code' => 'ECDIS','description' => 'Electronic Chart Display Information System','category' => 'Deck','duration' => '5','branch_id' => '2','created_by' => '1'],
            ['code' => 'AIS','description' => 'Automatic Identification System','category' => 'Deck','duration' => '2','branch_id' => '2','created_by' => '1'],
            ['code' => 'BRM','description' => 'Bridge Resource Management','category' => 'Deck','duration' => '3','branch_id' => '2','created_by' => '1'],
            ['code' => 'RFPNW','description' => 'Ratings Forming Part of Navigational Watch','category' => 'Deck','duration' => '5','branch_id' => '2','created_by' => '1'],
            ['code' => 'BTM','description' => 'Bridge Team Management','category' => 'Deck','duration' => '3','branch_id' => '2','created_by' => '1'],
            ['code' => 'MLCD-F1','description' => 'Function 1: Navigation at the Management Level','category' => 'Deck','duration' => '30','branch_id' => '2','created_by' => '1'],
            ['code' => 'MLCDU-F1','description' => 'Function 1: Updating Navigation at the Management Level','category' => 'Deck','duration' => '7','branch_id' => '2','created_by' => '1'],
            ['code' => 'MLCD-F2','description' => 'Function 2: Cargo Handling and Stowage at the Manage-ment Level','category' => 'Deck','duration' => '9','branch_id' => '2','created_by' => '1'],
            ['code' => 'MLCD-F3','description' => 'Function 3: Controlling of the Ship and Care of Person on Board','category' => 'Deck','duration' => '14','branch_id' => '2','created_by' => '1'],
            ['code' => 'MLCDU-F3','description' => 'Function 3: Updating Controlling of the Ship and Care of Person on Board','category' => 'Deck','duration' => '3','branch_id' => '2','created_by' => '1'],
            ['code' => 'OICU-DF1A','description' => 'Updating Training for Officer In Charge of a Navigational Watch F1 Part-A','category' => 'Deck','duration' => '7','branch_id' => '2','created_by' => '1'],
            ['code' => 'OICU-DF3A','description' => 'Updating Training for Officer In Charge of a Navigational Watch F3 Part-A','category' => 'Deck','duration' => '3','branch_id' => '2','created_by' => '1'],
            ['code' => 'OICU-DF1B','description' => 'Updating Training for Officer In Charge of a Navigational Watch F1 Part-B','category' => 'Deck','duration' => '12','branch_id' => '2','created_by' => '1'],
            ['code' => 'OICU-DF2B','description' => 'Updating Training for Officer In Charge of a Navigational Watch F2 Part-B','category' => 'Deck','duration' => '4','branch_id' => '2','created_by' => '1'],
            ['code' => 'OICU-DF3B','description' => 'Updating Training for Officer In Charge of Navigational Watch F3 Part-B','category' => 'Deck','duration' => '7','branch_id' => '2','created_by' => '1'],
            ['code' => 'ERSC with ERRM','description' => 'Engine Room Simulator Courses with Engine Room Resource Management','category' => 'Engine','duration' => '5','branch_id' => '2','created_by' => '1'],
            ['code' => 'ERRM','description' => 'Engine Room Resource Management','category' => 'Engine','duration' => '3','branch_id' => '2','created_by' => '1'],
            ['code' => 'ETM','description' => 'Engine Team Management','category' => 'Engine','duration' => '3','branch_id' => '2','created_by' => '1'],
            ['code' => 'RFPEW','description' => 'Ratings Forming Part of Engineering Watching','category' => 'Engine','duration' => '5','branch_id' => '2','created_by' => '1'],
            ['code' => 'AUMA','description' => 'Auxiliary Machinery','category' => 'Engine','duration' => '5','branch_id' => '2','created_by' => '1'],
            ['code' => 'COEN','description' => 'Control Engineering','category' => 'Engine','duration' => '5','branch_id' => '2','created_by' => '1'],
            ['code' => 'MLCE-F1','description' => 'FUNCTION 1: Marine Engineering at the Management Level','category' => 'Engine','duration' => '21','branch_id' => '2','created_by' => '1'],
            ['code' => 'MLCEU-F1','description' => 'FUNCTION 1: Updating Marine Engineering at the Management Level','category' => 'Engine','duration' => '10','branch_id' => '2','created_by' => '1'],
            ['code' => 'MLCE-F2','description' => 'FUNCTION 2: Electrical, Electronic and Control Engineer-ing at the Management Level','category' => 'Engine','duration' => '24','branch_id' => '2','created_by' => '1'],
            ['code' => 'MLCEU-F2','description' => 'FUNCTION 2: Updating Electrical, Electronic and Control Engineer-ing at the Management Level','category' => 'Engine','duration' => '17','branch_id' => '2','created_by' => '1'],
            ['code' => 'MLCE-F3','description' => 'FUNCTION 3: Maintenance and Repair at the Manage-ment Level','category' => 'Engine','duration' => '8','branch_id' => '2','created_by' => '1'],
            ['code' => 'MLCEU-F3','description' => 'FUNCTION 3: Updating Maintenance and Repair at the Manage-ment Level','category' => 'Engine','duration' => '4','branch_id' => '2','created_by' => '1'],
            ['code' => 'MLCE-F4','description' => 'FUNCTION 4: Controlling the Operation of the Ship and Care of Person on Board','category' => 'Engine','duration' => '18','branch_id' => '2','created_by' => '1'],
            ['code' => 'MLCEU-F4','description' => 'FUNCTION 4: Updating Controlling the Operation of the Ship and Care of Person on Board','category' => 'Engine','duration' => '3','branch_id' => '2','created_by' => '1'],
            ['code' => 'OICU-EF1A','description' => 'Updating Training for Officer In Charge of an Engineering Watch F1 Part-A','category' => 'Engine','duration' => '7','branch_id' => '2','created_by' => '1'],
            ['code' => 'OICU-EF2A','description' => 'Updating Training for Officer In Charge of an Engineering Watch F2 Part-A','category' => 'Engine','duration' => '2','branch_id' => '2','created_by' => '1'],
            ['code' => 'OICU-EF4A','description' => 'Updating Training for Officer In Charge of an Engineering Watch F4 Part-A','category' => 'Engine','duration' => '3','branch_id' => '2','created_by' => '1'],
            ['code' => 'OICU-EF1B','description' => 'Updating Training for Officer In Charge of Engineering Watch F1 Part-B','category' => 'Engine','duration' => '12','branch_id' => '2','created_by' => '1'],
            ['code' => 'OICU-EF2B','description' => 'Updating Training for Officer In Charge of Engineering Watch F2 Part-B','category' => 'Engine','duration' => '8','branch_id' => '2','created_by' => '1'],
            ['code' => 'OICU-EF4B','description' => 'Updating Training for Officer In Charge of Engineering Watch F4 Part-B','category' => 'Engine','duration' => '4','branch_id' => '2','created_by' => '1'],
            ['code' => 'MAR-E','description' => 'Maritime English','category' => 'Common','duration' => '5','branch_id' => '2','created_by' => '1'],
            ['code' => 'ANTI-PIRACY','description' => 'Anti-Piracy','category' => 'Common','duration' => '1','branch_id' => '2','created_by' => '1'],
            ['code' => 'MARPOL 1 TO 6','description' => 'Marine Pollution and Prevention (73/78 Annexes 1 to 6)','category' => 'Common','duration' => '5','branch_id' => '2','created_by' => '1'],
            ['code' => 'MARLAW','description' => 'Maritime Law for Ship Officers (for OIC)','category' => 'Common','duration' => '5','branch_id' => '2','created_by' => '1'],
            ['code' => 'MECA','description' => 'Medical Care','category' => 'Common','duration' => '5','branch_id' => '2','created_by' => '1'],
            ['code' => 'MEFA','description' => 'Medical Emergency First Aid','category' => 'Common','duration' => '4','branch_id' => '2','created_by' => '1'],
            ['code' => 'SDSDSAT','description' => 'Seafarer’s with Designated Security Duties and Security Awareness Training','category' => 'Common','duration' => '1','branch_id' => '2','created_by' => '1'],
            ['code' => 'BT','description' => 'Basic Training','category' => 'Common','duration' => '8','branch_id' => '2','created_by' => '1'],
            ['code' => 'BTOC','description' => 'Basic Training for Oil and Chemical Tanker','category' => 'Common','duration' => '6','branch_id' => '2','created_by' => '1'],
            ['code' => 'BTLGT','description' => 'Basic Training in Liquefied Gas Tanker','category' => 'Common','duration' => '6','branch_id' => '2','created_by' => '1'],
            ['code' => 'PSCRB','description' => 'Proficiency in Survival Craft an Rescue Boats','category' => 'Common','duration' => '4','branch_id' => '2','created_by' => '1'],
            ['code' => 'PFRB','description' => 'Profiency in Fast Rescue Boat','category' => 'Common','duration' => '4','branch_id' => '2','created_by' => '1'],
            ['code' => 'ATF','description' => 'Advance Training in Fire Fighting','category' => 'Common','duration' => '4','branch_id' => '2','created_by' => '1'],
            ['code' => 'MLCD-F1','description' => 'Function 1: Navigation at the Management Level','category' => 'Deck','duration' => '30','branch_id' => '5','created_by' => '1'],
            ['code' => 'MLCDU-F1','description' => 'Function 1: Updating Navigation at the Management Level','category' => 'Deck','duration' => '7','branch_id' => '5','created_by' => '1'],
            ['code' => 'MLCD-F2','description' => 'Function 2: Cargo Handling and Stowage at the Manage-ment Level','category' => 'Deck','duration' => '9','branch_id' => '5','created_by' => '1'],
            ['code' => 'MLCD-F3','description' => 'Function 3: Controlling of the Ship and Care of Person on Board','category' => 'Deck','duration' => '14','branch_id' => '5','created_by' => '1'],
            ['code' => 'MLCDU-F3','description' => 'Function 3: Updating Controlling of the Ship and Care of Person on Board','category' => 'Deck','duration' => '3','branch_id' => '5','created_by' => '1'],
            ['code' => 'OICU-DF1A','description' => 'Updating Training for Officer In Charge of a Navigational Watch F1 Part-A','category' => 'Deck','duration' => '7','branch_id' => '5','created_by' => '1'],
            ['code' => 'OICU-DF3A','description' => 'Updating Training for Officer In Charge of a Navigational Watch F3 Part-A','category' => 'Deck','duration' => '3','branch_id' => '5','created_by' => '1'],
            ['code' => 'OICU-DF1B','description' => 'Updating Training for Officer In Charge of a Navigational Watch F1 Part-B','category' => 'Deck','duration' => '12','branch_id' => '5','created_by' => '1'],
            ['code' => 'OICU-DF2B','description' => 'Updating Training for Officer In Charge of a Navigational Watch F2 Part-B','category' => 'Deck','duration' => '4','branch_id' => '5','created_by' => '1'],
            ['code' => 'OICU-DF3B','description' => 'Updating Training for Officer In Charge of Navigational Watch F3 Part-B','category' => 'Deck','duration' => '7','branch_id' => '5','created_by' => '1'],
            ['code' => 'SSBT with BRM','description' => 'Ship Simulator and Bridge Teamwork with BRM','category' => 'Deck','duration' => '5','branch_id' => '5','created_by' => '1'],
            ['code' => 'ECDIS','description' => 'Electronic Chart Display Information System','category' => 'Deck','duration' => '5','branch_id' => '5','created_by' => '1'],
            ['code' => 'AIS','description' => 'Automatic Identification System','category' => 'Deck','duration' => '2','branch_id' => '5','created_by' => '1'],
            ['code' => 'DW','description' => 'Deck Watchkeeping','category' => 'Deck','duration' => '5','branch_id' => '5','created_by' => '1'],
            ['code' => 'BRM','description' => 'Bridge Resource Management','category' => 'Deck','duration' => '3','branch_id' => '5','created_by' => '1'],
            ['code' => 'BTM','description' => 'Bridge Team Management','category' => 'Deck','duration' => '3','branch_id' => '5','created_by' => '1'],
            ['code' => 'DPAC','description' => 'SSBT Assessment','category' => 'Deck','duration' => '1','branch_id' => '5','created_by' => '1'],
            ['code' => 'MLCE-F1','description' => 'FUNCTION 1: Marine Engineering at the Management Level','category' => 'Engine','duration' => '21','branch_id' => '5','created_by' => '1'],
            ['code' => 'MLCEU-F1','description' => 'FUNCTION 1: Updating Marine Engineering at the Management Level','category' => 'Engine','duration' => '10','branch_id' => '5','created_by' => '1'],
            ['code' => 'MLCE-F2','description' => 'FUNCTION 2: Electrical, Electronic and Control Engineer-ing at the Management Level','category' => 'Engine','duration' => '24','branch_id' => '5','created_by' => '1'],
            ['code' => 'MLCEU-F2','description' => 'FUNCTION 2: Updating Electrical, Electronic and Control Engineer-ing at the Management Level','category' => 'Engine','duration' => '17','branch_id' => '5','created_by' => '1'],
            ['code' => 'MLCE-F3','description' => 'FUNCTION 3: Maintenance and Repair at the Manage-ment Level','category' => 'Engine','duration' => '8','branch_id' => '5','created_by' => '1'],
            ['code' => 'MLCEU-F3','description' => 'FUNCTION 3: Updating Maintenance and Repair at the Manage-ment Level','category' => 'Engine','duration' => '4','branch_id' => '5','created_by' => '1'],
            ['code' => 'MLCE-F4','description' => 'FUNCTION 4: Controlling the Operation of the Ship and Care of Person on Board','category' => 'Engine','duration' => '18','branch_id' => '5','created_by' => '1'],
            ['code' => 'MLCEU-F4','description' => 'FUNCTION 4: Updating Controlling the Operation of the Ship and Care of Person on Board','category' => 'Engine','duration' => '3','branch_id' => '5','created_by' => '1'],
            ['code' => 'OICU-EF1A','description' => 'Updating Training for Officer In Charge of an Engineering Watch F1 Part-A','category' => 'Engine','duration' => '7','branch_id' => '5','created_by' => '1'],
            ['code' => 'OICU-EF2A','description' => 'Updating Training for Officer In Charge of an Engineering Watch F2 Part-A','category' => 'Engine','duration' => '2','branch_id' => '5','created_by' => '1'],
            ['code' => 'OICU-EF4A','description' => 'Updating Training for Officer In Charge of an Engineering Watch F4 Part-A','category' => 'Engine','duration' => '3','branch_id' => '5','created_by' => '1'],
            ['code' => 'OICU-EF1B','description' => 'Updating Training for Officer In Charge of Engineering Watch F1 Part-B','category' => 'Engine','duration' => '12','branch_id' => '5','created_by' => '1'],
            ['code' => 'OICU-EF2B','description' => 'Updating Training for Officer In Charge of Engineering Watch F2 Part-B','category' => 'Engine','duration' => '8','branch_id' => '5','created_by' => '1'],
            ['code' => 'OICU-EF4B','description' => 'Updating Training for Officer In Charge of Engineering Watch F4 Part-B','category' => 'Engine','duration' => '4','branch_id' => '5','created_by' => '1'],
            ['code' => 'ERSC with ERRM','description' => 'Engine Room Simulator Courses with Engine Room Resource Management','category' => 'Engine','duration' => '5','branch_id' => '5','created_by' => '1'],
            ['code' => 'ETM','description' => 'Engine Team Management','category' => 'Engine','duration' => '3','branch_id' => '5','created_by' => '1'],
            ['code' => 'EW','description' => 'Engine Watchkeeping','category' => 'Engine','duration' => '5','branch_id' => '5','created_by' => '1'],
            ['code' => 'ERRM','description' => 'Engine Room Resource Management','category' => 'Engine','duration' => '3','branch_id' => '5','created_by' => '1'],
            ['code' => 'EPAC','description' => 'ERSC Assessment','category' => 'Engine','duration' => '1','branch_id' => '5','created_by' => '1'],
            ['code' => 'SSATSDSD','description' => 'Ship Security Awareness Training and Seafarers with Designated Security Duties','category' => 'Common','duration' => '1','branch_id' => '5','created_by' => '1'],
            ['code' => 'BT','description' => 'Basic Training','category' => 'Common','duration' => '8','branch_id' => '5','created_by' => '1'],
            ['code' => 'UTBS','description' => 'Updating Training for Basic Safety','category' => 'Common','duration' => '1','branch_id' => '5','created_by' => '1'],
            ['code' => 'RTBS','description' => 'Refresher Training for Basic Safety','category' => 'Common','duration' => '2','branch_id' => '5','created_by' => '1'],
            ['code' => 'PSCRB','description' => 'Proficiency in Survival Craft & Rescue Boat','category' => 'Common','duration' => '4','branch_id' => '5','created_by' => '1'],
            ['code' => 'PFRB','description' => 'Proficiency in Fast Rescue Boat','category' => 'Common','duration' => '3','branch_id' => '5','created_by' => '1'],
            ['code' => 'ATF','description' => 'Advance Training in Fire Fighting','category' => 'Common','duration' => '4','branch_id' => '5','created_by' => '1'],
            ['code' => 'FFLB','description' => 'Free Fall Life Boat','category' => 'Common','duration' => '1','branch_id' => '5','created_by' => '1'],
            ['code' => 'FFLBC','description' => 'Free Fall Lifeboat Course (Coxswain)','category' => 'Common','duration' => '2','branch_id' => '5','created_by' => '1'],
            ['code' => 'RATF','description' => 'Refresher Training on Advance Fire Fighting','category' => 'Common','duration' => '2','branch_id' => '5','created_by' => '1'],
            ['code' => 'RPSCRB','description' => 'Refresher Proficiency in Survival Craft & Rescue Boat','category' => 'Common','duration' => '2','branch_id' => '5','created_by' => '1'],
            ['code' => 'RPFRB','description' => 'Refresher Proficiency in Fast Rescue Boat','category' => 'Common','duration' => '2','branch_id' => '5','created_by' => '1'],
            ['code' => 'MARPOL 1 TO 6','description' => 'Marine Pollution and Prevention (73/78 Annexes 1 to 6)','category' => 'Common','duration' => '5','branch_id' => '5','created_by' => '1'],
            ['code' => 'MECA','description' => 'Medical Care','category' => 'Common','duration' => '5','branch_id' => '5','created_by' => '1'],
            ['code' => 'MEFA','description' => 'Medical Emergency First Aid','category' => 'Common','duration' => '4','branch_id' => '5','created_by' => '1'],
            ['code' => 'SSO','description' => 'Ship Security Officer Course','category' => 'Common','duration' => '3','branch_id' => '5','created_by' => '1'],
            ['code' => 'SD','description' => 'Smoke Diving','category' => 'Common','duration' => '2','branch_id' => '5','created_by' => '1'],
            ['code' => 'H2S','description' => 'Hydrogen Sulfide Awareness','category' => 'Common','duration' => '1','branch_id' => '5','created_by' => '1'],
            ['code' => 'BTOC','description' => 'Basic Training for Oil and Chemical Tanker','category' => 'Common','duration' => '6','branch_id' => '5','created_by' => '1'],
            ['code' => 'BTLGT','description' => 'Basic Training in Liquefied Gas Tanker','category' => 'Common','duration' => '6','branch_id' => '5','created_by' => '1'],
            ['code' => 'MLCD-F1','description' => 'Function 1: Navigation at the Management Level','category' => 'Deck','duration' => '30','branch_id' => '3','created_by' => '1'],
            ['code' => 'MLCDU-F1','description' => 'Function 1: Updating Navigation at the Management Level','category' => 'Deck','duration' => '7','branch_id' => '3','created_by' => '1'],
            ['code' => 'MLCD-F2','description' => 'Function 2: Cargo Handling and Stowage at the Manage-ment Level','category' => 'Deck','duration' => '9','branch_id' => '3','created_by' => '1'],
            ['code' => 'MLCD-F3','description' => 'Function 3: Controlling of the Ship and Care of Person on Board','category' => 'Deck','duration' => '14','branch_id' => '3','created_by' => '1'],
            ['code' => 'MLCDU-F3','description' => 'Function 3: Updating Controlling of the Ship and Care of Person on Board','category' => 'Deck','duration' => '3','branch_id' => '3','created_by' => '1'],
            ['code' => 'OICU-DF1A','description' => 'Updating Training for Officer In Charge of a Navigational Watch F1 Part-A','category' => 'Deck','duration' => '7','branch_id' => '3','created_by' => '1'],
            ['code' => 'OICU-DF3A','description' => 'Updating Training for Officer In Charge of a Navigational Watch F3 Part-A','category' => 'Deck','duration' => '3','branch_id' => '3','created_by' => '1'],
            ['code' => 'OICU-DF1B','description' => 'Updating Training for Officer In Charge of a Navigational Watch F1 Part-B','category' => 'Deck','duration' => '12','branch_id' => '3','created_by' => '1'],
            ['code' => 'OICU-DF2B','description' => 'Updating Training for Officer In Charge of a Navigational Watch F2 Part-B','category' => 'Deck','duration' => '4','branch_id' => '3','created_by' => '1'],
            ['code' => 'OICU-DF3B','description' => 'Updating Training for Officer In Charge of Navigational Watch F3 Part-B','category' => 'Deck','duration' => '7','branch_id' => '3','created_by' => '1'],
            ['code' => 'ECDIS','description' => 'Electronic Chart Display Information System','category' => 'Deck','duration' => '5','branch_id' => '3','created_by' => '1'],
            ['code' => 'RFPNW','description' => 'Ratings Forming Part of Navigational Watch','category' => 'Deck','duration' => '5','branch_id' => '3','created_by' => '1'],
            ['code' => 'MLCE-F1','description' => 'FUNCTION 1: Marine Engineering at the Management Level','category' => 'Engine','duration' => '21','branch_id' => '3','created_by' => '1'],
            ['code' => 'MLCEU-F1','description' => 'FUNCTION 1: Updating Marine Engineering at the Management Level','category' => 'Engine','duration' => '10','branch_id' => '3','created_by' => '1'],
            ['code' => 'MLCE-F2','description' => 'FUNCTION 2: Electrical, Electronic and Control Engineer-ing at the Management Level','category' => 'Engine','duration' => '24','branch_id' => '3','created_by' => '1'],
            ['code' => 'MLCEU-F2','description' => 'FUNCTION 2: Updating Electrical, Electronic and Control Engineer-ing at the Management Level','category' => 'Engine','duration' => '17','branch_id' => '3','created_by' => '1'],
            ['code' => 'MLCE-F3','description' => 'FUNCTION 3: Maintenance and Repair at the Manage-ment Level','category' => 'Engine','duration' => '8','branch_id' => '3','created_by' => '1'],
            ['code' => 'MLCEU-F3','description' => 'FUNCTION 3: Updating Maintenance and Repair at the Manage-ment Level','category' => 'Engine','duration' => '4','branch_id' => '3','created_by' => '1'],
            ['code' => 'MLCE-F4','description' => 'FUNCTION 4: Controlling the Operation of the Ship and Care of Person on Board','category' => 'Engine','duration' => '18','branch_id' => '3','created_by' => '1'],
            ['code' => 'MLCEU-F4','description' => 'FUNCTION 4: Updating Controlling the Operation of the Ship and Care of Person on Board','category' => 'Engine','duration' => '3','branch_id' => '3','created_by' => '1'],
            ['code' => 'OICU-EF1A','description' => 'Updating Training for Officer In Charge of an Engineering Watch F1 Part-A','category' => 'Engine','duration' => '7','branch_id' => '3','created_by' => '1'],
            ['code' => 'OICU-EF2A','description' => 'Updating Training for Officer In Charge of an Engineering Watch F2 Part-A','category' => 'Engine','duration' => '2','branch_id' => '3','created_by' => '1'],
            ['code' => 'OICU-EF4A','description' => 'Updating Training for Officer In Charge of an Engineering Watch F4 Part-A','category' => 'Engine','duration' => '3','branch_id' => '3','created_by' => '1'],
            ['code' => 'OICU-EF1B','description' => 'Updating Training for Officer In Charge of Engineering Watch F1 Part-B','category' => 'Engine','duration' => '12','branch_id' => '3','created_by' => '1'],
            ['code' => 'OICU-EF2B','description' => 'Updating Training for Officer In Charge of Engineering Watch F2 Part-B','category' => 'Engine','duration' => '8','branch_id' => '3','created_by' => '1'],
            ['code' => 'OICU-EF4B','description' => 'Updating Training for Officer In Charge of Engineering Watch F4 Part-B','category' => 'Engine','duration' => '4','branch_id' => '3','created_by' => '1'],
            ['code' => 'SSBT with BRM','description' => 'Ship Simulator and Bridge Teamwork with BRM','category' => 'Deck','duration' => '5','branch_id' => '3','created_by' => '1'],
            ['code' => 'ERSC with ERRM','description' => 'Engine Room Simulator Courses with Engine Room Resource Management','category' => 'Engine','duration' => '5','branch_id' => '3','created_by' => '1'],
            ['code' => 'MARPOL 1 TO 6','description' => 'Marine Pollution and Prevention (73/78 Annexes 1 to 6)','category' => 'Common','duration' => '5','branch_id' => '3','created_by' => '1'],
            ['code' => 'RFPEW','description' => 'Ratings Forming Part of Engineering Watch','category' => 'Engine','duration' => '5','branch_id' => '3','created_by' => '1'],
            ['code' => 'SSATSDSD','description' => 'Ship Security Awareness Training and Seafarers with Designated Security Duties','category' => 'Common','duration' => '1','branch_id' => '3','created_by' => '1'],
            ['code' => 'SSBT with BRM','description' => 'Ship Simulator and Bridge Teamwork with BRM','category' => 'Deck','duration' => '5','branch_id' => '1','created_by' => '1'],
            ['code' => 'ECDIS','description' => 'Electronic Chart Display Information System','category' => 'Deck','duration' => '5','branch_id' => '1','created_by' => '1'],
            ['code' => 'RNPUA','description' => 'Radar Navigation, Radar Plotting and Use of ARPA (ROPA)','category' => 'Deck','duration' => '8','branch_id' => '1','created_by' => '1'],
            ['code' => 'RFPNW','description' => 'Ratings Forming Part of Navigational Watch','category' => 'Deck','duration' => '6','branch_id' => '1','created_by' => '1'],
            ['code' => 'MLCD-F1','description' => 'Function 1: Navigation at the Management Level','category' => 'Deck','duration' => '30','branch_id' => '1','created_by' => '1'],
            ['code' => 'MLCD-F2','description' => 'Function 2: Cargo Handling and Stowage at the Manage-ment Level','category' => 'Deck','duration' => '9','branch_id' => '1','created_by' => '1'],
            ['code' => 'MLCD-F3','description' => 'Function 3: Controlling of the Ship and Care of Person on Board','category' => 'Deck','duration' => '14','branch_id' => '1','created_by' => '1'],
            ['code' => 'MLCDU-F1','description' => 'Function 1: Updating Navigation at the Management Level','category' => 'Deck','duration' => '7','branch_id' => '1','created_by' => '1'],
            ['code' => 'MLCDU-F3','description' => 'Function 3: Updating Controlling of the Ship and Care of Person on Board','category' => 'Deck','duration' => '3','branch_id' => '1','created_by' => '1'],
            ['code' => 'OICU-DF1A','description' => 'Updating Training for Officer In Charge of a Navigational Watch F1 Part-A','category' => 'Deck','duration' => '7','branch_id' => '1','created_by' => '1'],
            ['code' => 'OICU-DF1B','description' => 'Updating Training for Officer In Charge of a Navigational Watch F1 Part-B','category' => 'Deck','duration' => '12','branch_id' => '1','created_by' => '1'],
            ['code' => 'OICU-DF2B','description' => 'Updating Training for Officer In Charge of a Navigational Watch F2 Part-B','category' => 'Deck','duration' => '4','branch_id' => '1','created_by' => '1'],
            ['code' => 'OICU-DF3A','description' => 'Updating Training for Officer In Charge of a Navigational Watch F3 Part-A','category' => 'Deck','duration' => '3','branch_id' => '1','created_by' => '1'],
            ['code' => 'OICU-DF3B','description' => 'Updating Training for Officer In Charge of Navigational Watch F3 Part-B','category' => 'Deck','duration' => '7','branch_id' => '1','created_by' => '1'],
            ['code' => 'RFPEW','description' => 'Ratings Forming Part of Engineering Watch ','category' => 'Engine','duration' => '5','branch_id' => '1','created_by' => '1'],
            ['code' => 'ERSC with ERRM','description' => 'Engine Room Simulator Courses with Engine Room Resource Management','category' => 'Engine','duration' => '5','branch_id' => '1','created_by' => '1'],
            ['code' => 'MLCE-F1','description' => 'FUNCTION 1: Marine Engineering at the Management Level','category' => 'Engine','duration' => '21','branch_id' => '1','created_by' => '1'],
            ['code' => 'MLCE-F2','description' => 'FUNCTION 2: Electrical, Electronic and Control Engineer-ing at the Management Level','category' => 'Engine','duration' => '24','branch_id' => '1','created_by' => '1'],
            ['code' => 'MLCE-F3','description' => 'FUNCTION 3: Maintenance and Repair at the Manage-ment Level','category' => 'Engine','duration' => '8','branch_id' => '1','created_by' => '1'],
            ['code' => 'MLCE-F4','description' => 'FUNCTION 4: Controlling the Operation of the Ship and Care of Person on Board','category' => 'Engine','duration' => '18','branch_id' => '1','created_by' => '1'],
            ['code' => 'MLCEU-F1','description' => 'FUNCTION 1: Updating Marine Engineering at the Management Level','category' => 'Engine','duration' => '10','branch_id' => '1','created_by' => '1'],
            ['code' => 'MLCEU-F2','description' => 'FUNCTION 2: Updating Electrical, Electronic and Control Engineer-ing at the Management Level','category' => 'Engine','duration' => '17','branch_id' => '1','created_by' => '1'],
            ['code' => 'MLCEU-F3','description' => 'FUNCTION 3: Updating Maintenance and Repair at the Manage-ment Level','category' => 'Engine','duration' => '4','branch_id' => '1','created_by' => '1'],
            ['code' => 'MLCEU-F4','description' => 'FUNCTION 4: Updating Controlling the Operation of the Ship and Care of Person on Board','category' => 'Engine','duration' => '3','branch_id' => '1','created_by' => '1'],
            ['code' => 'OICU-EF1A','description' => 'Updating Training for Officer In Charge of an Engineering Watch F1 Part-A','category' => 'Engine','duration' => '7','branch_id' => '1','created_by' => '1'],
            ['code' => 'OICU-EF1B','description' => 'Updating Training for Officer In Charge of Engineering Watch F1 Part-B','category' => 'Engine','duration' => '12','branch_id' => '1','created_by' => '1'],
            ['code' => 'OICU-EF2A','description' => 'Updating Training for Officer In Charge of an Engineering Watch F2 Part-A','category' => 'Engine','duration' => '2','branch_id' => '1','created_by' => '1'],
            ['code' => 'OICU-EF2B','description' => 'Updating Training for Officer In Charge of Engineering Watch F2 Part-B','category' => 'Engine','duration' => '8','branch_id' => '1','created_by' => '1'],
            ['code' => 'OICU-EF4A','description' => 'Updating Training for Officer In Charge of an Engineering Watch F4 Part-A','category' => 'Engine','duration' => '3','branch_id' => '1','created_by' => '1'],
            ['code' => 'OICU-EF4B','description' => 'Updating Training for Officer In Charge of Engineering Watch F4 Part-B','category' => 'Engine','duration' => '4','branch_id' => '1','created_by' => '1'],
            ['code' => 'MARPOL 1 TO 6','description' => 'Marine Pollution and Prevention (73/78 Annexes 1 to 6)','category' => 'Common','duration' => '5','branch_id' => '1','created_by' => '1'],
            ['code' => 'SSATSDSD','description' => 'Ship Security Awareness Training and Seafarers with Designated Security Duties','category' => 'Common','duration' => '1','branch_id' => '1','created_by' => '1'],
            ['code' => 'SSO','description' => 'Ship Security Officer Course','category' => 'Common','duration' => '3','branch_id' => '1','created_by' => '1'],
            ['code' => 'MEFA','description' => 'Medical Emergency First Aid','category' => 'Common','duration' => '4','branch_id' => '1','created_by' => '1'],
            ['code' => 'SSBT with BRM','description' => 'Ship Simulator and Bridge Teamwork with BRM','category' => 'Deck','duration' => '5','branch_id' => '4','created_by' => '1'],
            ['code' => 'ECDIS','description' => 'Electronic Chart Display Information System','category' => 'Deck','duration' => '5','branch_id' => '4','created_by' => '1'],
            ['code' => 'RFPNW','description' => 'Ratings Forming Part of Navigational Watch','category' => 'Deck','duration' => '5','branch_id' => '4','created_by' => '1'],
            ['code' => 'RNPUA','description' => 'Radar Navigation, Radar Plotting and Use of ARPA (ROPA)','category' => 'Deck','duration' => '8','branch_id' => '4','created_by' => '1'],
            ['code' => 'MLCD-F1','description' => 'Function 1: Navigation at the Management Level','category' => 'Deck','duration' => '30','branch_id' => '4','created_by' => '1'],
            ['code' => 'MLCDU-F1','description' => 'Function 1: Updating Navigation at the Management Level','category' => 'Deck','duration' => '7','branch_id' => '4','created_by' => '1'],
            ['code' => 'MLCD-F2','description' => 'Function 2: Cargo Handling and Stowage at the Manage-ment Level','category' => 'Deck','duration' => '9','branch_id' => '4','created_by' => '1'],
            ['code' => 'MLCD-F3','description' => 'Function 3: Controlling of the Ship and Care of Person on Board','category' => 'Deck','duration' => '14','branch_id' => '4','created_by' => '1'],
            ['code' => 'MLCDU-F3','description' => 'Function 3: Updating Controlling of the Ship and Care of Person on Board','category' => 'Deck','duration' => '3','branch_id' => '4','created_by' => '1'],
            ['code' => 'OICU-DF1A','description' => 'Updating Training for Officer In Charge of a Navigational Watch F1 Part-A','category' => 'Deck','duration' => '7','branch_id' => '4','created_by' => '1'],
            ['code' => 'OICU-DF3A','description' => 'Updating Training for Officer In Charge of a Navigational Watch F3 Part-A','category' => 'Deck','duration' => '3','branch_id' => '4','created_by' => '1'],
            ['code' => 'OICU-DF1B','description' => 'Updating Training for Officer In Charge of a Navigational Watch F1 Part-B','category' => 'Deck','duration' => '12','branch_id' => '4','created_by' => '1'],
            ['code' => 'OICU-DF2B','description' => 'Updating Training for Officer In Charge of a Navigational Watch F2 Part-B','category' => 'Deck','duration' => '4','branch_id' => '4','created_by' => '1'],
            ['code' => 'OICU-DF3B','description' => 'Updating Training for Officer In Charge of Navigational Watch F3 Part-B','category' => 'Deck','duration' => '7','branch_id' => '4','created_by' => '1'],
            ['code' => 'RFPEW','description' => 'Ratings Forming Part of Engineering Watching','category' => 'Engine','duration' => '5','branch_id' => '4','created_by' => '1'],
            ['code' => 'ERSC with ERRM','description' => 'Engine Room Simulator Courses with Engine Room Resource Management','category' => 'Engine','duration' => '5','branch_id' => '4','created_by' => '1'],
            ['code' => 'MLCE-F1','description' => 'FUNCTION 1: Marine Engineering at the Management Level','category' => 'Engine','duration' => '21','branch_id' => '4','created_by' => '1'],
            ['code' => 'MLCEU-F1','description' => 'FUNCTION 1: Updating Marine Engineering at the Management Level','category' => 'Engine','duration' => '10','branch_id' => '4','created_by' => '1'],
            ['code' => 'MLCE-F2','description' => 'FUNCTION 2: Electrical, Electronic and Control Engineer-ing at the Management Level','category' => 'Engine','duration' => '24','branch_id' => '4','created_by' => '1'],
            ['code' => 'MLCEU-F2','description' => 'FUNCTION 2: Updating Electrical, Electronic and Control Engineer-ing at the Management Level','category' => 'Engine','duration' => '17','branch_id' => '4','created_by' => '1'],
            ['code' => 'MLCE-F3','description' => 'FUNCTION 3: Maintenance and Repair at the Manage-ment Level','category' => 'Engine','duration' => '8','branch_id' => '4','created_by' => '1'],
            ['code' => 'MLCEU-F3','description' => 'FUNCTION 3: Updating Maintenance and Repair at the Manage-ment Level','category' => 'Engine','duration' => '4','branch_id' => '4','created_by' => '1'],
            ['code' => 'MLCE-F4','description' => 'FUNCTION 4: Controlling the Operation of the Ship and Care of Person on Board','category' => 'Engine','duration' => '18','branch_id' => '4','created_by' => '1'],
            ['code' => 'MLCEU-F4','description' => 'FUNCTION 4: Updating Controlling the Operation of the Ship and Care of Person on Board','category' => 'Engine','duration' => '3','branch_id' => '4','created_by' => '1'],
            ['code' => 'OICU-EF1A','description' => 'Updating Training for Officer In Charge of an Engineering Watch F1 Part-A','category' => 'Engine','duration' => '7','branch_id' => '4','created_by' => '1'],
            ['code' => 'OICU-EF2A','description' => 'Updating Training for Officer In Charge of an Engineering Watch F2 Part-A','category' => 'Engine','duration' => '2','branch_id' => '4','created_by' => '1'],
            ['code' => 'OICU-EF4A','description' => 'Updating Training for Officer In Charge of an Engineering Watch F4 Part-A','category' => 'Engine','duration' => '3','branch_id' => '4','created_by' => '1'],
            ['code' => 'OICU-EF1B','description' => 'Updating Training for Officer In Charge of Engineering Watch F1 Part-B','category' => 'Engine','duration' => '12','branch_id' => '4','created_by' => '1'],
            ['code' => 'OICU-EF2B','description' => 'Updating Training for Officer In Charge of Engineering Watch F2 Part-B','category' => 'Engine','duration' => '8','branch_id' => '4','created_by' => '1'],
            ['code' => 'OICU-EF4B','description' => 'Updating Training for Officer In Charge of Engineering Watch F4 Part-B','category' => 'Engine','duration' => '4','branch_id' => '4','created_by' => '1'],
            ['code' => 'SSATSDSD','description' => 'Ship Security Awareness Training and Seafarers with Designated Security Duties','category' => 'Common','duration' => '1','branch_id' => '4','created_by' => '1'],
            ['code' => 'MARPOL 1 TO 6','description' => 'Marine Pollution and Prevention (73/78 Annexes 1 to 6)','category' => 'Common','duration' => '5','branch_id' => '4','created_by' => '1'],
            ['code' => 'MEFA','description' => 'Medical Emergency First Aid','category' => 'Common','duration' => '4','branch_id' => '4','created_by' => '1'],
            ['code' => 'SSO','description' => 'Ship Security Officer Course','category' => 'Common','duration' => '3','branch_id' => '4','created_by' => '1'],
            ['code' => 'BOSIET','description' => 'Basic Offshore Safety Induction and Emergency Training','category' => 'Off-Shore','duration' => '3','branch_id' => '4','created_by' => '1'],
            ['code' => 'HUET','description' => 'Helicopter Underwater Escape Training','category' => 'Off-Shore','duration' => '1','branch_id' => '4','created_by' => '1'],
            ['code' => 'FOET','description' => 'Further Offshore Emergency Training','category' => 'Off-Shore','duration' => '1','branch_id' => '4','created_by' => '1'],
            ['code' => 'T-HUET','description' => 'Tropical Helicopter Underwater Escape Training','category' => 'Off-Shore','duration' => '1','branch_id' => '4','created_by' => '1'],
            ['code' => 'T-FOET','description' => 'Tropical Further Offshore Emergency Training','category' => 'Off-Shore','duration' => '1','branch_id' => '4','created_by' => '1'],
            ['code' => 'BRIDGING','description' => 'Bridging Elements Training','category' => 'Off-Shore','duration' => '1','branch_id' => '4','created_by' => '1'],
            ['code' => 'EBS TBOSIET-THUET','description' => 'Emergency Breathing System (delivered in conjunction with T-BOSIET/T-HUET)','category' => 'Off-Shore','duration' => '1','branch_id' => '4','created_by' => '1'],
            ['code' => 'EBS TFOET','description' => 'Emergency Breathing System (delivered in conjunction with T-FOET)','category' => 'Off-Shore','duration' => '1','branch_id' => '4','created_by' => '1'],
            ['code' => 'ECT-IT','description' => 'Escape Chute Training Initial Training','category' => 'Off-Shore','duration' => '1','branch_id' => '4','created_by' => '1'],
            ['code' => 'ECT REF','description' => 'Escape Chute Training Refresher Training','category' => 'Off-Shore','duration' => '1','branch_id' => '4','created_by' => '1'],
            ['code' => 'MLCD-F1','description' => 'Function 1: Navigation at the Management Level','category' => 'Off-Shore','duration' => '30','branch_id' => '4','created_by' => '1'],
        ];

        foreach ($courses as $key => $course) {
            Course::create($course);
        }
    }
}
